print("=====================")
print("  Best Friend Maker")
print("=====================")
print("")
print("Hi. I'm the computer.")
name = input("What's your name?")
name = input(f"Hi, {name}! What's your favorite color?")
print(f"No way! My favorite color is also {name}!")
name = input("What's your favorite movie?")
print(f"What!!! My favorite movie is also {name}!")
name = input("What's your favorite game?")
print(f"Get out of here! My favorite game is {name},too!")
print("We like the same things! We should be best friends!")