# Write your code here :-)
print("=====================")
print("       Hello, World          ")
print("       by Skyler        ")
print("=====================")
print("")
print("Hello, World!!")
name = input("What Is Your Name? ")
print(f"Hello, {name}")